services:
  - docker
before_install:
  - docker build -t waritsan/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true waritsan/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  access-key-id: 
    secure: AWS_ACCESS_KEY
  secret-access-key: 
    secure: AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-707183154216"
  on:
    branch: master